CREATE TABLE "partnership_requests" (
	"id" serial PRIMARY KEY NOT NULL,
	"company_name" varchar(255) NOT NULL,
	"legal_name" varchar(255),
	"contact_first_name" varchar(100) NOT NULL,
	"contact_last_name" varchar(100) NOT NULL,
	"contact_email" varchar(255) NOT NULL,
	"contact_phone" varchar(50),
	"contact_role" varchar(100),
	"website" varchar(255),
	"description" text,
	"country" varchar(100),
	"address" text,
	"num_employees" integer,
	"annual_revenue" varchar(100),
	"category" varchar(50) NOT NULL,
	"partner_subcategory" varchar(100),
	"partnership_level" varchar(50),
	"motivations" text,
	"university_data" jsonb,
	"technology_data" jsonb,
	"status" varchar(50) DEFAULT 'en_attente',
	"is_accepted" boolean,
	"reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"rejection_reason" text,
	"created_partner_id" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
